// <auto-generated />
using System;
using DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(AlbumManagerDBContext))]
    partial class AlbumManagerDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MODELS.Concrete.Album", b =>
                {
                    b.Property<int>("AlbumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlbumId"));

                    b.Property<string>("AlbumName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar");

                    b.Property<decimal>("AlbumPrice")
                        .HasColumnType("money");

                    b.Property<DateTime>("AlbumReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AlbumSingerGroup")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("DiscountRate")
                        .HasColumnType("float");

                    b.Property<bool>("IsItOnSale")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.HasKey("AlbumId");

                    b.ToTable("Albums");

                    b.HasData(
                        new
                        {
                            AlbumId = 1,
                            AlbumName = "Tamirci Çıragı",
                            AlbumPrice = 200m,
                            AlbumReleaseDate = new DateTime(1997, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AlbumSingerGroup = "Cem Karaca",
                            CreationDate = new DateTime(2024, 6, 20, 23, 8, 44, 552, DateTimeKind.Local).AddTicks(3582),
                            DiscountRate = 15.0,
                            IsItOnSale = false,
                            Status = 1
                        },
                        new
                        {
                            AlbumId = 2,
                            AlbumName = "Thriller",
                            AlbumPrice = 200m,
                            AlbumReleaseDate = new DateTime(1982, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AlbumSingerGroup = "Michael Jackson",
                            CreationDate = new DateTime(2024, 6, 20, 23, 8, 44, 552, DateTimeKind.Local).AddTicks(3604),
                            DiscountRate = 10.0,
                            IsItOnSale = true,
                            Status = 1
                        },
                        new
                        {
                            AlbumId = 3,
                            AlbumName = "Thriller",
                            AlbumPrice = 200m,
                            AlbumReleaseDate = new DateTime(1982, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AlbumSingerGroup = "Michael Jackson",
                            CreationDate = new DateTime(2024, 6, 20, 23, 8, 44, 552, DateTimeKind.Local).AddTicks(3605),
                            DiscountRate = 10.0,
                            IsItOnSale = true,
                            Status = 1
                        },
                        new
                        {
                            AlbumId = 4,
                            AlbumName = "Dark Side of the Moon",
                            AlbumPrice = 250m,
                            AlbumReleaseDate = new DateTime(1973, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AlbumSingerGroup = "Pink Floyd",
                            CreationDate = new DateTime(2024, 6, 20, 23, 8, 44, 552, DateTimeKind.Local).AddTicks(3607),
                            DiscountRate = 15.0,
                            IsItOnSale = false,
                            Status = 1
                        },
                        new
                        {
                            AlbumId = 5,
                            AlbumName = "The Wall",
                            AlbumPrice = 300m,
                            AlbumReleaseDate = new DateTime(1979, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AlbumSingerGroup = "Pink Floyd",
                            CreationDate = new DateTime(2024, 6, 20, 23, 8, 44, 552, DateTimeKind.Local).AddTicks(3633),
                            DiscountRate = 20.0,
                            IsItOnSale = true,
                            Status = 1
                        },
                        new
                        {
                            AlbumId = 6,
                            AlbumName = "Back in Black",
                            AlbumPrice = 220m,
                            AlbumReleaseDate = new DateTime(1980, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AlbumSingerGroup = "AC/DC",
                            CreationDate = new DateTime(2024, 6, 20, 23, 8, 44, 552, DateTimeKind.Local).AddTicks(3635),
                            DiscountRate = 12.0,
                            IsItOnSale = true,
                            Status = 1
                        },
                        new
                        {
                            AlbumId = 7,
                            AlbumName = "Abbey Road",
                            AlbumPrice = 280m,
                            AlbumReleaseDate = new DateTime(1969, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AlbumSingerGroup = "The Beatles",
                            CreationDate = new DateTime(2024, 6, 20, 23, 8, 44, 552, DateTimeKind.Local).AddTicks(3637),
                            DiscountRate = 18.0,
                            IsItOnSale = false,
                            Status = 1
                        },
                        new
                        {
                            AlbumId = 8,
                            AlbumName = "The Eminem Show",
                            AlbumPrice = 210m,
                            AlbumReleaseDate = new DateTime(2002, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AlbumSingerGroup = "Eminem",
                            CreationDate = new DateTime(2024, 6, 20, 23, 8, 44, 552, DateTimeKind.Local).AddTicks(3639),
                            DiscountRate = 14.0,
                            IsItOnSale = true,
                            Status = 1
                        },
                        new
                        {
                            AlbumId = 9,
                            AlbumName = "Hotel California",
                            AlbumPrice = 260m,
                            AlbumReleaseDate = new DateTime(1976, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AlbumSingerGroup = "Eagles",
                            CreationDate = new DateTime(2024, 6, 20, 23, 8, 44, 552, DateTimeKind.Local).AddTicks(3641),
                            DiscountRate = 17.0,
                            IsItOnSale = false,
                            Status = 1
                        },
                        new
                        {
                            AlbumId = 10,
                            AlbumName = "Led Zeppelin IV",
                            AlbumPrice = 240m,
                            AlbumReleaseDate = new DateTime(1971, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AlbumSingerGroup = "Led Zeppelin",
                            CreationDate = new DateTime(2024, 6, 20, 23, 8, 44, 552, DateTimeKind.Local).AddTicks(3643),
                            DiscountRate = 16.0,
                            IsItOnSale = true,
                            Status = 1
                        },
                        new
                        {
                            AlbumId = 11,
                            AlbumName = "The Queen Is Dead",
                            AlbumPrice = 290m,
                            AlbumReleaseDate = new DateTime(1986, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AlbumSingerGroup = "The Smiths",
                            CreationDate = new DateTime(2024, 6, 20, 23, 8, 44, 552, DateTimeKind.Local).AddTicks(3644),
                            DiscountRate = 19.0,
                            IsItOnSale = false,
                            Status = 1
                        },
                        new
                        {
                            AlbumId = 12,
                            AlbumName = "Nevermind",
                            AlbumPrice = 270m,
                            AlbumReleaseDate = new DateTime(1991, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AlbumSingerGroup = "Nirvana",
                            CreationDate = new DateTime(2024, 6, 20, 23, 8, 44, 552, DateTimeKind.Local).AddTicks(3645),
                            DiscountRate = 20.0,
                            IsItOnSale = true,
                            Status = 1
                        },
                        new
                        {
                            AlbumId = 13,
                            AlbumName = "Future Nostalgia",
                            AlbumPrice = 25m,
                            AlbumReleaseDate = new DateTime(2020, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AlbumSingerGroup = "Dua Lipa",
                            CreationDate = new DateTime(2024, 6, 20, 23, 8, 44, 552, DateTimeKind.Local).AddTicks(3647),
                            DiscountRate = 10.0,
                            IsItOnSale = true,
                            Status = 1
                        },
                        new
                        {
                            AlbumId = 14,
                            AlbumName = "Positions",
                            AlbumPrice = 28m,
                            AlbumReleaseDate = new DateTime(2020, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AlbumSingerGroup = "Ariana Grande",
                            CreationDate = new DateTime(2024, 6, 20, 23, 8, 44, 552, DateTimeKind.Local).AddTicks(3649),
                            DiscountRate = 15.0,
                            IsItOnSale = false,
                            Status = 1
                        },
                        new
                        {
                            AlbumId = 15,
                            AlbumName = "evermore",
                            AlbumPrice = 30m,
                            AlbumReleaseDate = new DateTime(2020, 12, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AlbumSingerGroup = "Taylor Swift",
                            CreationDate = new DateTime(2024, 6, 20, 23, 8, 44, 552, DateTimeKind.Local).AddTicks(3650),
                            DiscountRate = 20.0,
                            IsItOnSale = true,
                            Status = 1
                        },
                        new
                        {
                            AlbumId = 16,
                            AlbumName = "After Hours",
                            AlbumPrice = 22m,
                            AlbumReleaseDate = new DateTime(2020, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AlbumSingerGroup = "The Weeknd",
                            CreationDate = new DateTime(2024, 6, 20, 23, 8, 44, 552, DateTimeKind.Local).AddTicks(3652),
                            DiscountRate = 12.0,
                            IsItOnSale = true,
                            Status = 1
                        },
                        new
                        {
                            AlbumId = 17,
                            AlbumName = "Fine Line",
                            AlbumPrice = 28m,
                            AlbumReleaseDate = new DateTime(2019, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AlbumSingerGroup = "Harry Styles",
                            CreationDate = new DateTime(2024, 6, 20, 23, 8, 44, 552, DateTimeKind.Local).AddTicks(3653),
                            DiscountRate = 18.0,
                            IsItOnSale = false,
                            Status = 1
                        },
                        new
                        {
                            AlbumId = 18,
                            AlbumName = "30",
                            AlbumPrice = 25m,
                            AlbumReleaseDate = new DateTime(2021, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AlbumSingerGroup = "Adele",
                            CreationDate = new DateTime(2024, 6, 20, 23, 8, 44, 552, DateTimeKind.Local).AddTicks(3655),
                            DiscountRate = 10.0,
                            IsItOnSale = true,
                            Status = 1
                        },
                        new
                        {
                            AlbumId = 19,
                            AlbumName = "Justice",
                            AlbumPrice = 28m,
                            AlbumReleaseDate = new DateTime(2021, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AlbumSingerGroup = "Justin Bieber",
                            CreationDate = new DateTime(2024, 6, 20, 23, 8, 44, 552, DateTimeKind.Local).AddTicks(3656),
                            DiscountRate = 0.0,
                            IsItOnSale = false,
                            Status = 1
                        },
                        new
                        {
                            AlbumId = 20,
                            AlbumName = "Happier Than Ever",
                            AlbumPrice = 30m,
                            AlbumReleaseDate = new DateTime(2021, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AlbumSingerGroup = "Billie Eilish",
                            CreationDate = new DateTime(2024, 6, 20, 23, 8, 44, 552, DateTimeKind.Local).AddTicks(3657),
                            DiscountRate = 20.0,
                            IsItOnSale = true,
                            Status = 1
                        },
                        new
                        {
                            AlbumId = 21,
                            AlbumName = "Montero",
                            AlbumPrice = 22m,
                            AlbumReleaseDate = new DateTime(2021, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AlbumSingerGroup = "Lil Nas X",
                            CreationDate = new DateTime(2024, 6, 20, 23, 8, 44, 552, DateTimeKind.Local).AddTicks(3659),
                            DiscountRate = 12.0,
                            IsItOnSale = true,
                            Status = 1
                        },
                        new
                        {
                            AlbumId = 22,
                            AlbumName = "Red (Taylor's Version)",
                            AlbumPrice = 28m,
                            AlbumReleaseDate = new DateTime(2021, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AlbumSingerGroup = "Taylor Swift",
                            CreationDate = new DateTime(2024, 6, 20, 23, 8, 44, 552, DateTimeKind.Local).AddTicks(3660),
                            DiscountRate = 0.0,
                            IsItOnSale = false,
                            Status = 1
                        },
                        new
                        {
                            AlbumId = 23,
                            AlbumName = "Karanlıkta",
                            AlbumPrice = 25m,
                            AlbumReleaseDate = new DateTime(2023, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AlbumSingerGroup = "Duman",
                            CreationDate = new DateTime(2024, 6, 20, 23, 8, 44, 552, DateTimeKind.Local).AddTicks(3661),
                            DiscountRate = 15.0,
                            IsItOnSale = true,
                            Status = 1
                        },
                        new
                        {
                            AlbumId = 24,
                            AlbumName = "Düşler Ülkesinin Gelgit Akşamları",
                            AlbumPrice = 28m,
                            AlbumReleaseDate = new DateTime(2023, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AlbumSingerGroup = "Müslüm Gürses",
                            CreationDate = new DateTime(2024, 6, 20, 23, 8, 44, 552, DateTimeKind.Local).AddTicks(3663),
                            DiscountRate = 0.0,
                            IsItOnSale = false,
                            Status = 1
                        },
                        new
                        {
                            AlbumId = 25,
                            AlbumName = "Aşk Masalı",
                            AlbumPrice = 30m,
                            AlbumReleaseDate = new DateTime(2023, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AlbumSingerGroup = "Sezen Aksu",
                            CreationDate = new DateTime(2024, 6, 20, 23, 8, 44, 552, DateTimeKind.Local).AddTicks(3664),
                            DiscountRate = 20.0,
                            IsItOnSale = true,
                            Status = 1
                        },
                        new
                        {
                            AlbumId = 26,
                            AlbumName = "Yaş Hikayesi",
                            AlbumPrice = 22m,
                            AlbumReleaseDate = new DateTime(2023, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AlbumSingerGroup = "Cem Adrian",
                            CreationDate = new DateTime(2024, 6, 20, 23, 8, 44, 552, DateTimeKind.Local).AddTicks(3665),
                            DiscountRate = 18.0,
                            IsItOnSale = true,
                            Status = 1
                        },
                        new
                        {
                            AlbumId = 27,
                            AlbumName = "Senin İçin Değer",
                            AlbumPrice = 28m,
                            AlbumReleaseDate = new DateTime(2023, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AlbumSingerGroup = "Kenan Doğulu",
                            CreationDate = new DateTime(2024, 6, 20, 23, 8, 44, 552, DateTimeKind.Local).AddTicks(3667),
                            DiscountRate = 12.0,
                            IsItOnSale = true,
                            Status = 1
                        },
                        new
                        {
                            AlbumId = 28,
                            AlbumName = "Gel Yeter",
                            AlbumPrice = 26m,
                            AlbumReleaseDate = new DateTime(2023, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AlbumSingerGroup = "Ajda Pekkan",
                            CreationDate = new DateTime(2024, 6, 20, 23, 8, 44, 552, DateTimeKind.Local).AddTicks(3668),
                            DiscountRate = 15.0,
                            IsItOnSale = false,
                            Status = 1
                        },
                        new
                        {
                            AlbumId = 29,
                            AlbumName = "Sorma Neden",
                            AlbumPrice = 32m,
                            AlbumReleaseDate = new DateTime(2023, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AlbumSingerGroup = "Tarkan",
                            CreationDate = new DateTime(2024, 6, 20, 23, 8, 44, 552, DateTimeKind.Local).AddTicks(3669),
                            DiscountRate = 10.0,
                            IsItOnSale = true,
                            Status = 1
                        },
                        new
                        {
                            AlbumId = 30,
                            AlbumName = "Düşler Sokağı",
                            AlbumPrice = 24m,
                            AlbumReleaseDate = new DateTime(2024, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AlbumSingerGroup = "Gülşen",
                            CreationDate = new DateTime(2024, 6, 20, 23, 8, 44, 552, DateTimeKind.Local).AddTicks(3671),
                            DiscountRate = 18.0,
                            IsItOnSale = false,
                            Status = 1
                        },
                        new
                        {
                            AlbumId = 31,
                            AlbumName = "Son Şarkılarım",
                            AlbumPrice = 29m,
                            AlbumReleaseDate = new DateTime(2024, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AlbumSingerGroup = "Teoman",
                            CreationDate = new DateTime(2024, 6, 20, 23, 8, 44, 552, DateTimeKind.Local).AddTicks(3672),
                            DiscountRate = 10.0,
                            IsItOnSale = true,
                            Status = 1
                        },
                        new
                        {
                            AlbumId = 32,
                            AlbumName = "Bir Zamanlar Türkiye'de",
                            AlbumPrice = 27m,
                            AlbumReleaseDate = new DateTime(2024, 6, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AlbumSingerGroup = "MFÖ",
                            CreationDate = new DateTime(2024, 6, 20, 23, 8, 44, 552, DateTimeKind.Local).AddTicks(3674),
                            DiscountRate = 15.0,
                            IsItOnSale = false,
                            Status = 1
                        },
                        new
                        {
                            AlbumId = 33,
                            AlbumName = "İstanbul Hatırası",
                            AlbumPrice = 25m,
                            AlbumReleaseDate = new DateTime(2023, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AlbumSingerGroup = "Müzeyyen Senar",
                            CreationDate = new DateTime(2024, 6, 20, 23, 8, 44, 552, DateTimeKind.Local).AddTicks(3675),
                            DiscountRate = 0.0,
                            IsItOnSale = true,
                            Status = 1
                        },
                        new
                        {
                            AlbumId = 34,
                            AlbumName = "Köprüaltı Çocukları",
                            AlbumPrice = 28m,
                            AlbumReleaseDate = new DateTime(2023, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AlbumSingerGroup = "Barış Manço",
                            CreationDate = new DateTime(2024, 6, 20, 23, 8, 44, 552, DateTimeKind.Local).AddTicks(3676),
                            DiscountRate = 0.0,
                            IsItOnSale = true,
                            Status = 1
                        });
                });

            modelBuilder.Entity("MODELS.Concrete.AlbumManager", b =>
                {
                    b.Property<int>("AlbumId")
                        .HasColumnType("int");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.HasKey("AlbumId", "ManagerId");

                    b.HasIndex("ManagerId");

                    b.ToTable("AlbumManagers");
                });

            modelBuilder.Entity("MODELS.Concrete.Manager", b =>
                {
                    b.Property<int>("ManagerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ManagerId"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar");

                    b.Property<string>("ManagerLastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.Property<string>("ManagerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.HasKey("ManagerId");

                    b.ToTable("Managers", (string)null);
                });

            modelBuilder.Entity("MODELS.Concrete.AlbumManager", b =>
                {
                    b.HasOne("MODELS.Concrete.Album", "Album")
                        .WithMany("AlbumManagers")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MODELS.Concrete.Manager", "Manager")
                        .WithMany("AlbumManagers")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("MODELS.Concrete.Album", b =>
                {
                    b.Navigation("AlbumManagers");
                });

            modelBuilder.Entity("MODELS.Concrete.Manager", b =>
                {
                    b.Navigation("AlbumManagers");
                });
#pragma warning restore 612, 618
        }
    }
}
